# origincar
main:
  laser_topic: /scan
  imu_topic: /imu
  odom_topic: /robotvel   # ieskf 加了轮速计之后就不怎么发散了
  
  localization_mode: true   # 定位模式(只更新base->odom, odom->map需要做重定位，重定位太麻烦了，在rviz中用2d pose estimate粗略弄一下得了)
  with_imu: 1   # 0: LO | 1:eskf LIO | 2:ieskf LIO
  delay_time: 5   # ms
frontend:
  kf_distance: 0.2   # default = 0.25
  kf_angle_deg: 30.0  # default = 30.0
  kf_add_scan_in_occu: 1 # 10个关键 scan 放入一次 occupancy map
  max_distance: 10.0     # 最远 10m (不包括 occupancy map)
  angle_boarder: 0.0
  imu_states_buffer_size: 10   # 去畸变的imu数据缓存
ndt:
  max_iter: 50           # 最大迭代次数
  voxel_size: 0.65        # 体素大小   单位 m / voxel   default = 0.2   太小的话可能在旋转的时候产生偏移
  min_effective_pts: 10  # 最近邻点数阈值   default = 10
  min_pts_in_voxel: 10   # 每个栅格中最小点数  default = 10
  max_pts_in_voxel: 50   # 每个栅格中最大点数  default = 50
  eps: 1e-3              # 停止优化的条件 通常取体素大小的1% 默认-1在程序中计算 default = 1e-3
  res_outlier_th: 5.661  # 卡方检验阈值（95%置信度）  基于马氏距离的卡方检验阈值。   default = 5.661
  capacity: 10000         # 缓存的体素数量   default = 100000
  normalizing_factor: 1e-3  # 正则化因子
  init_info: 1e3         # 初始化 voxel 信息矩阵
  nearby_type: 2         # 0:center | 1:4 | 2:8 (default)
occupancy_map:
  closest_th: 0.1         # MODEL_POINTS 近距离阈值            default = 0.1
  endpoint_close_th: 0.1  # MODEL_POINTS 末端点障碍物近距离阈值 default = 0.1
  resolution: 20.0        # 1m 多少像素  default=20.0
  image_size: 200        # 图像大小

imu:
  imu_dt: 0.01   # 0.01s 即 100Hz   检查时间戳用的
  # 噪声设为负数，系统自动计算
  bax: -0.0506324
  bay: 0.453892
  bg: -0.0270514
  gyro_var: 2e-1
  acce_var: 2e-2
  bias_gyro_var: -1
  bias_acce_var: -1
  odom_var: 0.5  # 轮速计噪声   正数则在预积分中加入 odom 观测
  update_bias_gyro: true   # 迭代过程中是否更新 bg
  update_bias_acce: true   # 迭代过程中是否更新 ba
  eskf:
    imu_dt: 0.01   # 0.01s 即 100Hz
    lidar_pos_noise: 0.01
    lidar_ang_noise: 0.01 # 1 x pi / 180 = 0.01745329251994329576923690768489

  ieskf:
    imu_dt: 0.01   # 0.01s 即 100Hz
    num_iterations: 10 # 迭代次数
    eps: 1e-3          # 终止迭代的dx大小
    info_ratio: 0.01    # 每个点反馈的info因子
    